package entities;

// Generated 15:58:51 06/05/2016 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "demo")
@XmlRootElement(name = "product")
public class Product implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String phone;
	private String service;
	private String startdate;
	private String enddate;

	public Product() {
	}

	public Product(String name, String email, String phone, String service,
			String startdate, String enddate) {
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.service = service;
		this.startdate = startdate;
		this.enddate = enddate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 65535)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", nullable = false, length = 65535)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = false, length = 65535)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "service", nullable = false, length = 65535)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "startdate", nullable = false, length = 65535)
	public String getStartdate() {
		return this.startdate;
	}

	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	@Column(name = "enddate", nullable = false, length = 65535)
	public String getEnddate() {
		return this.enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

}
